-- MySQL Script generated by MySQL Workbench
-- Thu Mar 15 17:25:49 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`meal_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`meal_type` (
  `meal_type_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`meal_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recipe` (
  `recipe_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `prepation_time` INT NULL,
  `cooking_time` INT NULL,
  `servings` INT NULL,
  `ratings` INT NULL,
  `meal_type_id` INT NOT NULL,
  `picture` VARCHAR(45) NULL,
  PRIMARY KEY (`recipe_id`),
  INDEX `fk_recipe_meal_type_idx` (`meal_type_id` ASC),
  CONSTRAINT `fk_recipe_meal_type`
    FOREIGN KEY (`meal_type_id`)
    REFERENCES `mydb`.`meal_type` (`meal_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`preparation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`preparation` (
  `recipe_id` INT NOT NULL,
  `step` INT NOT NULL,
  `description` VARCHAR(100) NULL,
  INDEX `fk_preparation_recipe1_idx` (`recipe_id` ASC),
  PRIMARY KEY (`recipe_id`, `step`),
  CONSTRAINT `fk_preparation_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `mydb`.`recipe` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingridient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingridient` (
  `ingridient_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`ingridient_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recipe_ingridient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recipe_ingridient` (
  `recipe_id` INT NOT NULL,
  `ingridient_id` INT NOT NULL,
  `quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`recipe_id`, `ingridient_id`),
  INDEX `fk_recipe_has_ingridient_ingridient1_idx` (`ingridient_id` ASC),
  INDEX `fk_recipe_has_ingridient_recipe1_idx` (`recipe_id` ASC),
  CONSTRAINT `fk_recipe_has_ingridient_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `mydb`.`recipe` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_has_ingridient_ingridient1`
    FOREIGN KEY (`ingridient_id`)
    REFERENCES `mydb`.`ingridient` (`ingridient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  `picture` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recipe_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recipe_category` (
  `recipe_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`recipe_id`, `category_id`),
  INDEX `fk_recipe_has_category_category1_idx` (`category_id` ASC),
  INDEX `fk_recipe_has_category_recipe1_idx` (`recipe_id` ASC),
  CONSTRAINT `fk_recipe_has_category_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `mydb`.`recipe` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_has_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member_recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member_recipe` (
  `username` VARCHAR(20) NOT NULL,
  `recipe_id` INT NOT NULL,
  PRIMARY KEY (`username`, `recipe_id`),
  INDEX `fk_member_has_recipe_recipe1_idx` (`recipe_id` ASC),
  INDEX `fk_member_has_recipe_member1_idx` (`username` ASC),
  CONSTRAINT `fk_member_has_recipe_member1`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`member` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_has_recipe_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `mydb`.`recipe` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NULL,
  `user_type` VARCHAR(45) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `username` VARCHAR(20) NOT NULL,
  `preferred_schedule` VARCHAR(45) NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_employee_user1_idx` (`username` ASC),
  CONSTRAINT `fk_employee_user1`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `start_date` VARCHAR(45) NULL,
  `end_date` VARCHAR(45) NULL,
  `schedule` VARCHAR(45) NULL,
  `employee_id` INT NOT NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`course_id`),
  INDEX `fk_course_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_course_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `fk_student_user1_idx` (`username` ASC),
  CONSTRAINT `fk_student_user1`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cancelation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cancelation` (
  `course_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  INDEX `fk_cancelation_course1_idx` (`course_id` ASC),
  PRIMARY KEY (`date`, `course_id`),
  CONSTRAINT `fk_cancelation_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_course` (
  `student_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`student_id`, `course_id`),
  INDEX `fk_student_has_course_course1_idx` (`course_id` ASC),
  INDEX `fk_student_has_course_student1_idx` (`student_id` ASC),
  CONSTRAINT `fk_student_has_course_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_course_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`course` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
